### ISSUE TITLE
Sometime, I get the error with PayPal::getOrder( ) 

### ISSUE THREAD

**Issue by mrminthu** [paypal/Checkout-PHP-SDK#31] opened 2019-10-01 06:27 UTC
production.ERROR: HTTP response does not have Content-Type header set {"exception":"[object] (Exception(code: 0): HTTP response does not have Content-Type header set at

vendor\\braintree\\braintreehttp\\lib\\BraintreeHttp\\Encoder.php:58

Hi , when I call get order method - PayPal::getOrder(__order_id__), I get the above message. Most of the call are ok but sometime, this issue happen.

Please kindly suggest me about this issue. Thanks

**Comment by bmewburn** [comment] 2019-10-01 12:32
I've found this has been happening frequently lately. Please fix.

**Comment by tems99** [comment] 2019-10-01 15:27
I am also getting the same error.
Message: HTTP response does not have Content-Type header set

ex: "#0 /var/www/vendor/braintree/braintreehttp/lib/BraintreeHttp/HttpClient.php(176): BraintreeHttp\Encoder->deserializeResponse('{"scope":"https...', Array)
#1 /var/www/vendor/braintree/braintreehttp/lib/BraintreeHttp/HttpClient.php(97): BraintreeHttp\HttpClient->parseResponse(Object(BraintreeHttp\Curl))
#2 /var/www/vendor/paypal/paypal-checkout-sdk/lib/PayPalCheckoutSdk/Core/AuthorizationInjector.php(37): BraintreeHttp\HttpClient->execute(Object(PayPalCheckoutSdk\Core\AccessTokenRequest))
#3 /var/www/vendor/paypal/paypal-checkout-sdk/lib/PayPalCheckoutSdk/Core/AuthorizationInjector.php(29): PayPalCheckoutSdk\Core\AuthorizationInjector->fetchAccessToken()
#4 /var/www/vendor/braintree/braintreehttp/lib/BraintreeHttp/HttpClient.php(64): PayPalCheckoutSdk\Core\AuthorizationInjector->inject(Object(PayPalCheckoutSdk\Orders\OrdersCreateRequest))
#5 /var/www/BarkotaShippingSystemLib/src/Domain/Payments/Gateways/Paypal/PaypalClient.php(65): BraintreeHttp\HttpClient->execute(Object(PayPalCheckoutSdk\Orders\OrdersCreateRequest))

**Comment by ganeshramc** [comment] 2019-10-01 15:29
We’re looking into this! Thanks for reaching out. Will let you guys know an update soon

**Comment by mrminthu** [comment] 2019-10-01 16:13
Hi, thanks for reply. Currently is happening every order.

Now I cannot call both getOrder and also captureOrder methods. All are returning this content-type error

**Comment by ganeshramc** [comment] 2019-10-01 16:15
Could you provide an order id from a call in production please?

**Comment by mrminthu** [comment] 2019-10-01 16:17
1. 0EU28208GD505125X
2. 0PH24911FE494921N
3. 8VE77692DD682573H

You may reference to this error log in case if you need it. 
<img width="786" alt="Untitled" src="https://user-images.githubusercontent.com/14970356/65980571-091d5000-e4aa-11e9-9284-cea215188830.png">

**Comment by ganeshramc** [comment] 2019-10-01 16:20
Thanks for that! Looking into it

**Comment by ganeshramc** [comment] 2019-10-01 16:32
@mrminthu the orders are going through fine. The orders are being captured as well. So the money will be in your account but looking into why content-type is not being set.

**Comment by mrminthu** [comment] 2019-10-01 16:35
Previous days, this issue affected to only a few orders but starting today from four or five hour ago, this issue is affecting to every order.

**Comment by mrminthu** [comment] 2019-10-01 16:45
Sandbox environment is ok, Only happening at the production environment. 
Just now I also tested with different server and still getting the same error for getOrder and captureOrder methods.

**Comment by ganeshramc** [comment] 2019-10-01 16:50
Okay thanks! We do see from our side that it's not being set as well. Looking for a resolutions

**Comment by ganeshramc** [comment] 2019-10-01 17:09
@mrminthu could you try something for me? Could you do `$headersFromResponse = implode("|", $response->headers);` in production enviroment and print it and add the value for that here?

**Comment by mrminthu** [comment] 2019-10-01 17:25
Please wait, I will try to get the response headers at at BraintreeHttp\HttpClient.php

**Comment by mrminthu** [comment] 2019-10-01 17:47
The below is the CURL response body from HttpClient.php line no 170 ($body = $responseData;)

The exception throw after that at line no 176 ($responseBody = $this->encoder->deserializeResponse($body, $headers);)

{"scope":"https://uri.paypal.com/services/invoicing https://uri.paypal.com/services/disputes/read-buyer https://uri.paypal.com/services/payments/realtimepayment https://uri.paypal.com/services/disputes/update-seller https://uri.paypal.com/services/payments/payment/authcapture openid https://uri.paypal.com/services/disputes/read-seller https://uri.paypal.com/services/payments/refund https://api.paypal.com/v1/vault/credit-card https://api.paypal.com/v1/payments/.* https://uri.paypal.com/payments/payouts https://api.paypal.com/v1/vault/credit-card/.* https://uri.paypal.com/services/subscriptions https://uri.paypal.com/services/applications/webhooks","access_token":"A21AAGizUWZokn_ulZq8jkHMMDs2WKYT0CcULqZvkLMZet4AmFfafbNglwZlU86DLdKmd27aD9E1QVDOSkmy9LCynYig7wpKA","token_type":"Bearer","app_id":"APP-2ME37928KB3472010","expires_in":30807,"nonce":"2019-10-01T17:16:39ZEbAXKB3KcF7y9lRTfC1OfTAU2UVZa57xiVExfb8JM3c"}

**Comment by mrminthu** [comment] 2019-10-01 18:06
You mean this one ?

Array
(
    [] => 
    [Cache-Control] => max-age=0, no-cache, no-store, must-revalidate
    [Content-Length] => 918
    [Content-Type] => application/json
    [Date] => Tue, 01 Oct 2019 18
    [Paypal-Debug-Id] => b8bc12e675808
    [X-Paypal-Token-Service] => IAAS
)

By the way, just now I can see there is one successful payment. I am not sure the service are back to normal or not.

**Comment by ganeshramc** [comment] 2019-10-01 18:08
Great. I see content-type now. Continue monitoring from your side and please continue to log the headers as well. The next time you get an issue, that will be useful information to see why this is occuring.

**Comment by mrminthu** [comment] 2019-10-01 18:11
I am still getting the error. The problem still haven't solved yet.

**Comment by mrminthu** [comment] 2019-10-01 18:17
Sometime, I get success response but sometime, i get the exception. It seem like not stable.

Below one is successful response.. It does have "Content-type". But I will monitor for the failed response and get back to you.

Array
(
    [] => 
    [Cache-Control] => max-age=0, no-cache, no-store, must-revalidate
    [Content-Length] => 1128
    [Content-Type] => application/json
    [Date] => Tue, 01 Oct 2019 18
    [Paypal-Debug-Id] => 91cda734295b4
)
</pre><pre>BraintreeHttp\HttpResponse Object
(
    [statusCode] => 200
    [result] => stdClass Object
        (
            [id] => 40T59504273104212
            [intent] => CAPTURE
            [purchase_units] => Array
                (
                    [0] => stdClass Object
                        (
                            [reference_id] => B1908014
                            [amount] => stdClass Object
                                (
                                    [currency_code] => SGD
                                    [value] => 30.00
                                    [breakdown] => stdClass Object
                                        (
                                            [item_total] => stdClass Object
                                                (
                                                    [currency_code] => SGD
                                                    [value] => 30.00
                                                )

                                        )

                                )

**Comment by ganeshramc** [comment] 2019-10-01 18:19
Thanks. Please do since we are not able to reproduce this issue from our side

**Comment by mrminthu** [comment] 2019-10-01 18:20
This one is the failed response. Seem like "Content-Type " in small letter

<pre>Array
(
    [] => 
    [content-type] => application/json
    [content-length] => 918
    [cache-control] => max-age=0, no-cache, no-store, must-revalidate
    [date] => Tue, 01 Oct 2019 18
    [paypal-debug-id] => c1293f2b1c3cb
    [x-paypal-token-service] => IAAS
    [strict-transport-security] => max-age=31536000; includeSubDomains
)
</pre>{
    "message": "HTTP response does not have Content-Type header set",
    "exception": "Exception",
    "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\braintree\\braintreehttp\\lib\\BraintreeHttp\\Encoder.php",
    "line": 60,
    "trace": [
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\braintree\\braintreehttp\\lib\\BraintreeHttp\\HttpClient.php",
            "line": 176,
            "function": "deserializeResponse",
            "class": "BraintreeHttp\\Encoder",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\braintree\\braintreehttp\\lib\\BraintreeHttp\\HttpClient.php",
            "line": 97,
            "function": "parseResponse",
            "class": "BraintreeHttp\\HttpClient",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\paypal\\paypal-checkout-sdk\\lib\\PayPalCheckoutSdk\\Core\\AuthorizationInjector.php",
            "line": 37,
            "function": "execute",
            "class": "BraintreeHttp\\HttpClient",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\paypal\\paypal-checkout-sdk\\lib\\PayPalCheckoutSdk\\Core\\AuthorizationInjector.php",
            "line": 29,
            "function": "fetchAccessToken",
            "class": "PayPalCheckoutSdk\\Core\\AuthorizationInjector",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\braintree\\braintreehttp\\lib\\BraintreeHttp\\HttpClient.php",
            "line": 64,
            "function": "inject",
            "class": "PayPalCheckoutSdk\\Core\\AuthorizationInjector",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\app\\Libraries\\Payment\\PayPal\\PayPal.php",
            "line": 82,
            "function": "execute",
            "class": "BraintreeHttp\\HttpClient",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\app\\Http\\Requests\\MyERA\\Event\\EventRegistrationRequest.php",
            "line": 95,
            "function": "getOrder",
            "class": "App\\Libraries\\Payment\\PayPal\\PayPal",
            "type": "::"
        },
        {
            "function": "App\\Http\\Requests\\MyERA\\Event\\{closure}",
            "class": "App\\Http\\Requests\\MyERA\\Event\\EventRegistrationRequest",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Validation\\Validator.php",
            "line": 253,
            "function": "call_user_func_array"
        },
        {
            "function": "Illuminate\\Validation\\{closure}",
            "class": "Illuminate\\Validation\\Validator",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Validation\\Validator.php",
            "line": 289,
            "function": "call_user_func"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Validation\\Validator.php",
            "line": 302,
            "function": "passes",
            "class": "Illuminate\\Validation\\Validator",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Validation\\ValidatesWhenResolvedTrait.php",
            "line": 25,
            "function": "fails",
            "class": "Illuminate\\Validation\\Validator",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Providers\\FormRequestServiceProvider.php",
            "line": 30,
            "function": "validateResolved",
            "class": "Illuminate\\Foundation\\Http\\FormRequest",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php",
            "line": 1086,
            "function": "Illuminate\\Foundation\\Providers\\{closure}",
            "class": "Illuminate\\Foundation\\Providers\\FormRequestServiceProvider",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php",
            "line": 1050,
            "function": "fireCallbackArray",
            "class": "Illuminate\\Container\\Container",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php",
            "line": 1035,
            "function": "fireAfterResolvingCallbacks",
            "class": "Illuminate\\Container\\Container",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php",
            "line": 691,
            "function": "fireResolvingCallbacks",
            "class": "Illuminate\\Container\\Container",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php",
            "line": 619,
            "function": "resolve",
            "class": "Illuminate\\Container\\Container",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php",
            "line": 757,
            "function": "make",
            "class": "Illuminate\\Container\\Container",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\RouteDependencyResolverTrait.php",
            "line": 79,
            "function": "make",
            "class": "Illuminate\\Foundation\\Application",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\RouteDependencyResolverTrait.php",
            "line": 46,
            "function": "transformDependency",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\RouteDependencyResolverTrait.php",
            "line": 27,
            "function": "resolveMethodDependencies",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php",
            "line": 41,
            "function": "resolveClassMethodDependencies",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php",
            "line": 219,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php",
            "line": 176,
            "function": "runController",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 680,
            "function": "run",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
            "line": 30,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\app\\Http\\Middleware\\VerifyAssociate.php",
            "line": 38,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "App\\Http\\Middleware\\VerifyAssociate",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 104,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 682,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 657,
            "function": "runRouteWithinStack",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 623,
            "function": "runRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 612,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
            "line": 176,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
            "line": 30,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\fideloper\\proxy\\src\\TrustProxies.php",
            "line": 57,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Fideloper\\Proxy\\TrustProxies",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php",
            "line": 27,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php",
            "line": 62,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 104,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
            "line": 151,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
            "line": 116,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\laraveloauth\\public\\index.php",
            "line": 55,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        }
    ]
}

**Comment by ganeshramc** [comment] 2019-10-01 18:21
I see. Okay thank you. We'll fix this!

**Comment by bmewburn** [comment] 2019-10-01 20:41
Thanks for looking at this. Was there a fix? As I understand it, http headers are not required to be title cased, but the dependency to this package that is handling this expects them to be (braintree/braintreehttp). Also https://github.com/braintree/braintreehttp_php appears to be archived. So was the fix on paypal servers?

Given that
> This is a part of the next major PayPal SDK

And official guides suggest using this SDK. It's a little worrying it could break like this, require an end user to debug it for paypal, and then there not be a way to move forward because the sdk relies on a package that has been archived and not committed to for over a year.

**Comment by bmewburn** [comment] 2019-10-01 21:45
Still an issue.

**Comment by ganeshramc** [comment] 2019-10-01 21:48
@bmewburn we are still working on it to see why this is happening. We are planning to fix it server side and since this is a one off use case and it was from client side and we couldn't reproduce it from our side, we unfortunately couldn't debug it using our logs. We greatly appreciate support from you guys in helping debug this.

**Comment by bmewburn** [comment] 2019-10-01 21:59
@ganeshramc  I appreciate the effort. Unfortunately in the meantime it completely breaks live implementations using this SDK. In my case payments are being captured but I am unable to complete the order process because I can't confirm capture, leading to a lot of support tickets.

**Comment by bmewburn** [comment] 2019-10-01 22:14
Temp fix:
vendor\braintree\braintreehttp\lib\BraintreeHttp\Encoder.php
```php
public function deserializeResponse($responseBody, $headers)
    {
        $contentType = null;
        if (array_key_exists('Content-Type', $headers)) {
            $contentType = $headers['Content-Type'];
        } else if (array_key_exists('content-type', $headers)) {
            $contentType = $headers['content-type'];
        } else {
            throw new \Exception("HTTP response does not have Content-Type header set");
        }

        /** @var Serializer $serializer */
        $serializer = $this->serializer($contentType);

        if (is_null($serializer)) {
            throw new \Exception(sprintf("Unable to deserialize response with Content-Type: %s. Supported encodings are: %s", $contentType, implode(", ", $this->supportedEncodings())));
        }

        if (
            (array_key_exists("Content-Encoding", $headers) && $headers["Content-Encoding"] === "gzip") ||
            (array_key_exists("content-encoding", $headers) && $headers["content-encoding"] === "gzip")
        ) {
            $responseBody = gzdecode($responseBody);
        }

        return $serializer->decode($responseBody);
    }
```

**Comment by ganeshramc** [comment] 2019-10-02 00:26
Thank you for the temporary fix @bmewburn. We are working with internal teams to figure this out since this is not consistent behavior across several merchants but @mrminthu @tems99 please follow the changes as above. We are working on a more permanent fix with a new release of the sdk soon as well. Thanks again everyone for your help and contributions.

**Comment by mrminthu** [comment] 2019-10-02 01:24
@bmewburn thanks for your temp fix. @ganeshramc thanks for your support also. Please kindly let us know after you fix this issue (or) new release of the sdk.

**Comment by ganeshramc** [comment] 2019-10-02 20:47
This issue should be fixed now! We will also be issuing a new release for the SDK soon which we would really appreciate if you guys took time to upgrade to that! We'll let you know once we release a new version.

**Comment by tiffanyrzhou** [comment] 2020-01-10 01:27
Beginning January 2020, PayPal will require an update on the Personal Home Page (PHP) Checkout Software Developer Kit (SDK) to version 1.0.1. Merchants who have not updated their PHP Checkout SDK to version 1.0.1 will not be able to deserialize responses using outdated SDK integrations.
All PHP Checkout SDK integrations are expected to be updated by March 1, 2020. Merchants are encouraged to prepare for the update as soon as possible to avoid possible service disruption.
The Status Page has been updated with this information. The bulletin can be found [here](https://www.paypal-status.com/history/eventdetails/11015)

**Closed** 2020-06-13 06:59 UTC
